# Generated by Django 3.2 on 2021-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='descrpition',
            field=models.TextField(default='old dojo'),
        ),
    ]
